### PR TITLE
Fix Clair CPU Restrictions

### LINKED ISSUE #1805: 1.4.0 OVA panics on resource starvation
Bug Report Basic Information
----------------------------

REQUIRED:

- vCenter Server version: 6.7
- Embedded or external PSC: Embedded
- Filename of the OVA you deployed: Dev build - off master, after 1.4.0
- How was the OVA deployed? (Flex client, HTML5 client, ovftool): ovftool
- Does the VIC appliance recieve configuration by DHCP? yes
- What stage of the Appliance Lifecycle is the VIC appliance in? running (broken)?
  https://github.com/vmware/vic-product/blob/master/installer/docs/SUPPORT.md#appliance-lifecycle
- Attach the VIC appliance support bundle (e.g. vic_appliance_logs_2018-01-01-00-01-00.tar.gz)
  https://github.com/vmware/vic-product/blob/master/installer/docs/SUPPORT.md#appliance-support-bundle
  Note: The support bundle may contain private information. If you are not comfortable with posting this publicly, please contact VMware GSS.

OPTIONAL, but helpful:

- IP address of VIC appliance:
- Hostname of VIC appliance:
- IP address of vCenter Server:
- Hostname of vCenter Server:

ping @morris-jason for the IP and support bundle.

Bug Report Detailed Information
-------------------------------

Appliance is in a bad state following what looks like continual harbor failures. This issue was first reported to me by @pdaigle on a 1.4.0 GA OVA. See below:

From Patrick:

>It turns out the VIC Appliance was in pretty bad shape (which is surprising because I have not used it in a week). When I first tried to grab a log bundle it got stuck because the script could not run `docker ps`. I rebooted the appliance but the Harbor service failed. I noticed that the `dch-push` container was behaving strangely and generating errors in the logs. I eventually fixed it by:
 
>Stopping the Harbor service (systemctl stop harbor);
>Manually removing the dch-push container (docker rm dch-push);
>Rebooting the appliance (shutdown -r now);
 

My conjecture is that harbor is restarting indefinitely after entering a bad state, which is trashing systemd and docker.

In the harbor journal from the bundle, I see this error:
```
May 12 00:05:32 registry.corp.local start_harbor.sh[99471]: Exception in thread Thread-27:
May 12 00:05:42 registry.corp.local start_harbor.sh[99471]: Traceback (most recent call last):
May 12 00:05:53 registry.corp.local start_harbor.sh[99471]: File "threading.py", line 801, in __bootstrap_inner
May 12 00:05:59 registry.corp.local start_harbor.sh[99471]: File "threading.py", line 754, in run
May 12 00:06:05 registry.corp.local start_harbor.sh[99471]: File "compose/cli/log_printer.py", line 197, in watch_events
May 12 00:06:12 registry.corp.local start_harbor.sh[99471]: File "compose/project.py", line 369, in events
May 12 00:06:20 registry.corp.local start_harbor.sh[99471]: File "compose/container.py", line 42, in from_id
May 12 00:06:26 registry.corp.local start_harbor.sh[99471]: File "site-packages/docker/utils/decorators.py", line 21, in wrapped
May 12 00:06:30 registry.corp.local start_harbor.sh[99471]: File "site-packages/docker/api/container.py", line 736, in inspect_container
May 12 00:06:36 registry.corp.local start_harbor.sh[99471]: File "site-packages/docker/utils/decorators.py", line 47, in inner
May 12 00:06:40 registry.corp.local start_harbor.sh[99471]: File "site-packages/docker/api/client.py", line 179, in _get
May 12 00:06:43 registry.corp.local start_harbor.sh[99471]: File "site-packages/requests/sessions.py", line 488, in get
May 12 00:06:47 registry.corp.local start_harbor.sh[99471]: File "site-packages/requests/sessions.py", line 475, in request
May 12 00:06:51 registry.corp.local start_harbor.sh[99471]: File "site-packages/requests/sessions.py", line 596, in send
May 12 00:06:53 registry.corp.local start_harbor.sh[99471]: File "site-packages/requests/adapters.py", line 499, in send
May 12 00:06:56 registry.corp.local start_harbor.sh[99471]: ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
May 12 00:09:15 registry.corp.local start_harbor.sh[99471]: harbor-jobservice exited with code 0
```

Which precedes a system reboot. This may not be an error - it's possibly just the python threading module dealing with the signals for a reboot.
However, at this point, everything had been up fine for ~3.5 days.

From this point on (after May 13th) Harbor is up for about 7 days, off and on, restarting itself occasionally due to errors.

When the harbor startup logs *don't* have the above error, they have this error (2,356 times over 2.5 days):
An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
 
 
These started on May 20th and continued until May 22nd.

After this, the docker logs are littered with (430 times over 3 hours):
docker: Error response from daemon: driver failed programming external connectivity on endpoint dch-push (<container-id>): Bind for 0.0.0.0:5000 failed: port is already allocated.
These started on May 22nd and continued until you rebooted the appliance.

 

Following the May 12th reboot above, there is another jobservice crash before the HTTP error above starts showing up:

```
May 20 00:21:28 registry.corp.local start_harbor.sh[1292]: Exception in thread Thread-27:
May 20 00:21:43 registry.corp.local start_harbor.sh[1292]: Traceback (most recent call last):
May 20 00:22:03 registry.corp.local start_harbor.sh[1292]: File "threading.py", line 801, in __bootstrap_inner
May 20 00:22:34 registry.corp.local start_harbor.sh[1292]: File "threading.py", line 754, in run
May 20 00:24:12 registry.corp.local start_harbor.sh[1292]: File "compose/cli/log_printer.py", line 197, in watch_events
May 20 00:26:42 registry.corp.local start_harbor.sh[1292]: File "compose/project.py", line 369, in events
May 20 00:27:50 registry.corp.local start_harbor.sh[1292]: File "compose/container.py", line 42, in from_id
May 20 00:28:06 registry.corp.local start_harbor.sh[1292]: File "site-packages/docker/utils/decorators.py", line 21, in wrapped
May 20 00:28:15 registry.corp.local start_harbor.sh[1292]: File "site-packages/docker/api/container.py", line 736, in inspect_container
May 20 00:28:40 registry.corp.local start_harbor.sh[1292]: File "site-packages/docker/utils/decorators.py", line 47, in inner
May 20 00:29:06 registry.corp.local start_harbor.sh[1292]: File "site-packages/docker/api/client.py", line 179, in _get
May 20 00:29:28 registry.corp.local start_harbor.sh[1292]: File "site-packages/requests/sessions.py", line 488, in get
May 20 00:31:25 registry.corp.local systemd[1]: harbor.service: Main process exited, code=exited, status=255/n/a
```

I am experiencing similar issues on a master dev build.

@reasonerjt can you please assign someone to investigate from the Harbor team?
@pdaigle please comment if I missed anything.

### PR DESCRIPTION
**Pull request by morris-jason**
VIC Appliance Checklist:
- [x] Up to date with `master` branch
- [ ] Added tests
- [ ] Considered impact to upgrade
- [x] Tests passing
- [ ] Updated documentation
- [ ] Impact assessment checklist

Removes journal logsize limit, restricts Clair cpu usage, and adds kernel debugging logs to the appliance support bundle.
Fixes #1805

Request for 1.4.1 cherry pick.

### CODE REVIEW

File: installer/build/scripts/provisioners/provision_harbor.sh [hunk 1]
```diff
@@ -36,8 +36,10 @@ f = open(file, "r+")
 dataMap = yaml.safe_load(f)
 for _, s in enumerate(dataMap["services"]):
   if "restart" in dataMap["services"][s]:
-      if "always" in dataMap["services"][s]["restart"] and s != "jobservice":
-        dataMap["services"][s]["restart"] = "on-failure"
+    if "always" in dataMap["services"][s]["restart"] and s != "jobservice":
```
Comment (reasonerjt) [inline installer/build/scripts/provisioners/provision_harbor.sh]: I think this line is no longer needed.

Comment (morris-jason) [reply installer/build/scripts/provisioners/provision_harbor.sh]: Done.
